### ISSUE TITLE
From-Points at dead-ends for OD Matrix

### ISSUE THREAD

**Issue by Athelena** [root676/QNEAT3#46] opened 2021-04-01 15:40 UTC
Thanks for these tools, my colleague and I find them really helpful! 

We did find a quirk that we think could do with some thinking about. We have a point that is at a dead-end between two 1-way lanes going in opposite directions: 

![image](https://user-images.githubusercontent.com/19203377/113315851-02c19b80-930e-11eb-8073-f465debd3b42.png)

It seems the point is choosing the top lane to access the network, but because it's choosing the dead-end of a 1-way lane it is ignored in the calculation because it cannot access any of the To-Points. If we change these dead-ends From-Points to be To-Points instead, they can now be accessed. 

We have several examples like this in our dataset since we find it rather common to have large facilities connected to dead-end entry and exit lanes.

**Comment by root676** [comment] 2021-04-01 21:49
Thanks for pointing this out. Unfortunately there is no way to fix this on the software side. The only solution is to physically move the point towards the link you want it to connect to. The problem is rooted in the underlying QGIS network analysis classes that QNEAT3 uses. When points are tied to the network edges, the points jump to the nearest edge (which seems to be the wrong one in your case). Currently is no way for the point to figure out that the edge it is assigned to is a dead end.

**Comment by josephholler** [comment] 2021-04-02 00:50
I second @root676. You would likely have the same problem in any network analysis software. I'd suggest creating a two-way line between your end points in each of these scenarios so that routing could go either way no matter which end point the facility ties to. You might even be able to figure out a way to create these lines automatically by searching for end points with one-way values within a small distance.

**Comment by Athelena** [comment] 2021-04-02 12:40
Yes we had the same thought process as well and did connecting lines between the ends points. And indeed it had failed in Arc as well. To be honest we thought more to share it as a curiosity since we didn't figure out the issue right away. So many things can go wrong when working with a network 😅  So we thought we'd raise the issue in case anybody else forgot to consider this. 

Again thanks so much for your great tools and looking forward to what's to come next 😃

**Comment by root676** [comment] 2021-04-02 13:17
Thanks for raising this and thanks for this solution path @josephholler. Network analysis can raise some tricky problems sometimes :wink:

**Closed by root676** 2021-04-02 13:17 UTC
